### ISSUE TITLE
Bower can't find this package

### ISSUE THREAD

**Issue by cherrellem** [samwiseduzer/angularPrint#19]
I try installing it by typing the command "bower install AngularPrint"
and its reply is "bower ENOTFOUND     Package AngularPrint not found"

**Comment by pelizza** [comment]
The correct usage is:

`bower install angular-print`

**Comment by cherrellem** [comment]
Thanks, Pelizza! 

Sorry, I didn't read the instructions before opening an issue.

**Comment by cherrellem** [comment]
@samwiseduzer This package is great! Thank you for sharing! It made my life so much easier. :+1: 

From:
Happy coder :)
