### ISSUE TITLE
print-btn and ng-click

### ISSUE THREAD

**Issue by donnygunawan93** [samwiseduzer/angularPrint#27]
`<button print-btn ng-click="getData()">Click</button>`

when button pressed...yes will show print preview, but doFunction() will not run until print popup closed.
cause I need value from getData(), can we call print-btn from getData() ?

**Comment by cjbrooks12** [comment]
If you look at the source, the `print-btn` directive does nothing more than add a click handler which calls `$window.print();`. Try adding that at the end of your `getData()` function.
