### ISSUE TITLE
print-remove doesn't function on td

### ISSUE THREAD

**Issue by alecava58** [samwiseduzer/angularPrint#4]
I'd like to hide the button that is on every cell of a column, but I don't know if I did well:

```
                <td>
                    <div print-remove>
                        <div class="btn btn-primary btn-xs" ng-click="printQuiz($index)">
                            <span class="glyphicon glyphicon-print"></span> Stampa
                        </div>
                    </div>
                </td>
```

**Comment by alecava58** [comment]
Not sure if it is true. Let me check again,

**Comment by samwiseduzer** [comment]
Could you show me a little more of your code? From the ng-repeat should be fine.

**Comment by alecava58** [comment]
Never mind, there was my fault

Alessandro

On Tue, Oct 6, 2015 at 3:18 PM -0700, "samwiseduzer" notifications@github.com wrote:

Could you show me a little more of your code? From the ng-repeat should be fine.
